import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Extractor, ExtractorConfig } from '@microsoft/api-extractor'
import { getEsmExportNames, getPublishedPackages } from './public-packages.mjs'

let ROOT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..')
let REPORT_DIR = join(ROOT_DIR, 'api-reports')
let TEMP_DIR = join(ROOT_DIR, 'node_modules', '.cache', 'api-reports')
let RUNTIME_REPORT = join(REPORT_DIR, 'runtime-exports.api.md')
let UPDATE_REPORTS = process.argv.includes('--update')
const DOCUMENTED_PACKAGES = new Set([
  'core',
  'experiments',
  'hydrogen',
  'next',
  'react',
  'schema',
])
let publishedPackages = getPublishedPackages(ROOT_DIR)
let typeEntrypoints = publishedPackages.flatMap((publishedPackage) =>
  publishedPackage.entrypoints
    .filter((entrypoint) => entrypoint.types)
    .map((entrypoint) => ({ publishedPackage, entrypoint }))
)

mkdirSync(REPORT_DIR, { recursive: true })
mkdirSync(TEMP_DIR, { recursive: true })

let failed = false

for (let { publishedPackage, entrypoint } of typeEntrypoints) {
  let { folderName, folder } = publishedPackage
  let reportName = `${folderName}${
    entrypoint.subpath === '.'
      ? ''
      : `.${entrypoint.subpath.slice(2).replaceAll('/', '.')}`
  }`
  let extractorConfig = ExtractorConfig.prepare({
    configObject: {
      projectFolder: folder,
      mainEntryPointFilePath: join(folder, entrypoint.types),
      compiler: {
        tsconfigFilePath: join(folder, 'tsconfig.json'),
        skipLibCheck: true,
      },
      apiReport: {
        enabled: true,
        reportFileName: reportName,
        reportFolder: REPORT_DIR,
        reportTempFolder: TEMP_DIR,
      },
      docModel: { enabled: false },
      dtsRollup: { enabled: false },
      tsdocMetadata: { enabled: false },
      messages: {
        compilerMessageReporting: {
          default: { logLevel: 'error' },
        },
        extractorMessageReporting: {
          default: { logLevel: 'error' },
          'ae-forgotten-export': { logLevel: 'error' },
          'ae-missing-release-tag': { logLevel: 'none' },
          'ae-undocumented': {
            logLevel: DOCUMENTED_PACKAGES.has(folderName) ? 'error' : 'none',
          },
          'ae-unresolved-link': { logLevel: 'error' },
        },
        tsdocMessageReporting: {
          default: { logLevel: 'none' },
        },
      },
    },
    configObjectFullPath: undefined,
    packageJsonFullPath: join(folder, 'package.json'),
  })

  let result = Extractor.invoke(extractorConfig, {
    localBuild: UPDATE_REPORTS,
    printApiReportDiff: true,
    showVerboseMessages: false,
  })

  if (!result.succeeded) {
    failed = true
  }
}

let runtimeExports = {}
let entrypointBySpecifier = new Map(
  typeEntrypoints.map((entry) => [entry.entrypoint.specifier, entry])
)

function collectRuntimeExports(specifier) {
  if (runtimeExports[specifier]) {
    return runtimeExports[specifier]
  }

  let entry = entrypointBySpecifier.get(specifier)
  if (!entry?.entrypoint.import) {
    throw new Error(`Cannot resolve runtime exports for ${specifier}`)
  }

  let names = getEsmExportNames(
    join(entry.publishedPackage.folder, entry.entrypoint.import),
    collectRuntimeExports
  )
  runtimeExports[specifier] = names
  return names
}

for (let { entrypoint } of typeEntrypoints) {
  if (entrypoint.import) {
    collectRuntimeExports(entrypoint.specifier)
  }
}

let runtimeReport = `## Runtime Export Report

> Do not edit this file. Run \`pnpm run api:report\` after intentional public runtime changes.

\`\`\`json
${JSON.stringify(runtimeExports, null, 2)}
\`\`\`
`
if (UPDATE_REPORTS) {
  writeFileSync(RUNTIME_REPORT, runtimeReport)
} else if (
  !existsSync(RUNTIME_REPORT) ||
  readFileSync(RUNTIME_REPORT, 'utf8') !== runtimeReport
) {
  console.error(
    'Runtime exports changed. Run `pnpm run api:report` and review the diff.'
  )
  failed = true
}

if (failed) {
  process.exitCode = 1
}
