import Head from 'next/head'
import {Thing, WeaverseSDK} from '@weaverse/sdk-react'


const Workspace = () => {
    let reactSDK = new WeaverseSDK()
    return <div>
        <Thing sdk={reactSDK}/>
    </div>
}

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Workspace/>
      </div>
  )
}
