name: Claude Code

on:
  # Automatic PR reviews
  pull_request:
    types: [opened, synchronize]
  # Manual triggers via @claude mentions
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  # Automatic PR review job
  claude-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          
          # Direct prompt for automated review
          direct_prompt: |
            Review this PR for the Weaverse SDKs monorepo. Focus on high-impact issues and provide actionable feedback.
            
            **Critical Checks:**
            • Breaking changes requiring major version bumps
            • Cross-package dependency conflicts or misaligned versions
            • Missing changesets for user-facing changes
            • Security vulnerabilities or exposed secrets
            • Performance regressions in core SDK functionality
            
            **Architecture & Quality:**
            • TypeScript type safety - flag any `any` usage or unsafe patterns
            • Framework-agnostic design in @weaverse/core (no React/framework deps)
            • Proper error handling and edge cases
            • Memory leaks or resource cleanup issues
            • API design consistency across packages
            
            **SDK-Specific:**
            • Component schema validation and prop handling
            • Data connector performance and immutability
            • Hydrogen/React integration patterns
            • Export statements and package entry points
            • Template system changes affecting backward compatibility
            
            **Skip routine items** (unless critical): formatting, minor naming, basic linting.
            **Prioritize** issues that could break user implementations or degrade SDK performance.
            
            Provide specific line references and concrete suggestions for fixes.

          # Use sticky comments to update the same comment
          use_sticky_comment: true

  # Manual trigger job for @claude mentions
  claude-mention:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read

